FROM openjdk:17

WORKDIR /usrapp/bin

EXPOSE 8080

COPY /target/classes /usrapp/bin/classes
COPY /target/dependency /usrapp/bin/dependency


CMD ["java","-cp","./classes:./dependency/*","edu.eci.arep.ASE.app.Main"]